name: goreleaser

on:
  push:
    tags:
      - v*

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Start Report
        uses: act10ns/slack@v1.2.2
        if: always()
        with:
          status: starting
          channel: '#github-actions'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TOKEN }}

      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        id: installGo
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Lint
        id: lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.11.4

      - name: Create Release
        id: createRelease
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Slack Finish Report
        uses: act10ns/slack@v1.2.2
        if: always()
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#github-actions'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TOKEN }}
